### ISSUE TITLE
Consider uploading docker images to a docker registry

### ISSUE THREAD

**Issue by HaavardM** [AscendNTNU/control_simulator#16]
Just an idea!

Could be built and uploaded by the jenkins build server. Precompiled images would be downloaded when needed by docker compose! The docker compose file would also be a lot cleaner, since it wont need to build the images! :) 

I think Ascend has a docker registry server running somewhere. At least we had one at some point.
Or you could use Docker Hub! 

Super fan of your work btw <3

**Comment by rendellc** [comment]
Ah yes! 
It would also save a lot of time building the images! I think I'll delay since I might be making some bigger changes soon

**Comment by rendellc** [comment]
#21
